# SPDX-FileCopyrightText: 2022 James R. Barlow
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
        exclude: \.rst$
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.7
    hooks:
      - id: clang-format
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "-a", "from __future__ import annotations"]
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.247"
    hooks:
      - id: ruff
        files: "src/.*\\.pyi?$"
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        additional_dependencies:
          - lxml-stubs
          - types-Pillow
          - types-requests
          - types-setuptools
